services:
  - type: web
    name: basketball-position-analytics
    env: python
    plan: free
    buildCommand: python -m pip install -r requirements.txt && python init_db.py
    startCommand: gunicorn --chdir . my_flask_app.app:app
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        generateValue: true